# Pipeline for building our SageOneApi.Client NuGet

trigger: none
# trigger:
#  branches:
#    include:
#    - refs/heads/master
#  batch: True

name: 0.2.0-CI-$(Date:yyyyMMdd)-$(Rev:rrr)

variables:
  buildConfiguration: 'Debug'
  packageVersion: $(Build.BuildNumber)
# Variable 'PFXHash' is defined in the Variables tab
# Variable 'PasswordForPFXfile' is defined in the Variables tab

jobs:

- job: Phase_1
  displayName: Phase 1
  cancelTimeoutInMinutes: 1
  pool:
    vmImage: windows-2019
  steps:

  - script: |
      echo 'Right, off we go then'
      echo 'Build.BuildNumber: $(Build.BuildNumber)'
      echo 'buildConfiguration: $(buildConfiguration)'
      echo 'packageVersion: $(packageVersion)'
      echo 'Build.ArtifactStagingDirectory: $(Build.ArtifactStagingDirectory)'
      echo 'Pipeline.Workspace: $(Pipeline.Workspace)'
      echo 'System.DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)'

  - checkout: self

  - task: DownloadSecureFile@1
    displayName: Download secure file
    inputs:
      secureFile: e4a99c4f-86be-4d7f-a331-df06b41dc8d4
      retryCount: 5

  - task: PowerShell@2
    displayName: Install PFX
    inputs:
      targetType: inline
      script: >-
        $password = "$(PasswordForPFXfile)" | ConvertTo-SecureString -AsPlainText -Force

        Import-PfxCertificate -FilePath "$(Agent.WorkFolder)\_temp\LS Code 2019.pfx" -CertStoreLocation Cert:\CurrentUser\My -Password $password

  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet '
    inputs:
      checkLatest: true

  - task: NuGetCommand@2
    name: NuGetCommand1
    displayName: NuGet restore
    inputs:
      solution: SageOneApi.sln
      searchPatternPush: $(Build.ArtifactStagingDirectory)/*.nupkg

  - task: DotNetCoreCLI@2
    displayName: 'build all'
    inputs:
      command: 'build'
      projects: 'SageOneApi.sln'
      arguments: '-c $(buildConfiguration)'

# Having set GeneratePackageOnBuild in the project config, there's no need for a separate NuGet build step.

  - task: CopyFiles@2
    displayName: 'Copy to artifacts'
    inputs:
      SourceFolder: 'SageOneApi.Client/bin/$(BuildConfiguration)'
      Contents: '*.*'
      TargetFolder: '$(Build.ArtifactStagingDirectory)\mybin'
    continueOnError: true
    enabled: true

  - powershell: gci env:* | sort-object name | Format-Table -AutoSize | Out-File $env:BUILD_ARTIFACTSTAGINGDIRECTORY/environment-variables.txt

  - powershell: Get-ChildItem -Path $env:PIPELINE_WORKSPACE -recurse | Out-File $env:BUILD_ARTIFACTSTAGINGDIRECTORY/directory-structure.txt

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop

  - task: NuGetCommand@2
    name: NuGetCommand4
    displayName: NuGet push
    inputs:
      command: push
      searchPatternPush: '$(Build.ArtifactStagingDirectory)\**\SageOneApi*.nupkg'
      feedPublish: aeaa4311-673f-4791-a14d-d19ad82f0603
...
